Qinxiangshuge/urls.py
from django.contrib import admin
from django.urls import path, include

from novels.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('user/', include('user.urls', namespace='user')),
    path('novels/', include('novels.urls', namespace='novels')),
]

novels/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.views import serve
from django.urls import path, include

from Qinxiangshuge.settings import MEDIA_ROOT
from novels.views import *

app_name = 'novels'

urlpatterns = [
    url(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    url(r'^tinymce/', include('tinymce.urls')),
    path('index', index, name='index'),
    path('search', search, name='search'),
    path('detail/<str:gid>', novel_detail, name='detail'),
    path('novelbody/<str:uid>', novel_body, name='novelbody'),
    path('add_bookrack', add_bookrack, name='add_bookrack'),
    path('show_bookrack', show_bookrack, name='show_bookrack'),
    path('add_chapter', add_chapter, name='add_chapter'),
    path('delete_collect/<str:uid>', delete_collect, name='delete_collect'),
    path('category_show/<str:tid>', category_show, name='category_show'),
    path('novel_hits', novel_hits, name='novel_hits'),
    path('all_novels', all_novels, name='all_novels'),
    path('ranking_list', ranking_list, name='ranking_list'),
    path('author_edit', author_edit, name='author_edit'),
    path('author_add_capther/<str:uid>', author_add_capther, name='author_add_capther'),
    path('show_author_novels', show_author_novels, name='show_author_novels'),
    path('author_delete_novel/<str:uid>', author_delete_novel, name='author_delete_novel'),
]

user/urls.py
from django.urls import path

from user.views import user_login, user_register, user_send_code, user_draw, find_pwd, modify_pwd, user_logout,test_baidu

app_name = 'user'

urlpatterns = [
    path('login', user_login, name='login'),
    path('register', user_register, name='register'),
    path('send_code', user_send_code, name='send_code'),
    path('draw', user_draw, name='draw'),
    path('find_pwd', find_pwd, name='find_pwd'),
    path('modify_pwd', modify_pwd, name='modify_pwd'),
    path('logout', user_logout, name='logout'),
    path('test_report', test_baidu, name='test_baidu'),
]

novels/models.py
from django.db import models

from user.models import User
from tinymce.models import HTMLField

class NovelsType(models.Model):
    '''小说类别表'''
    typename = models.CharField(max_length=30, verbose_name='小说类别名称')
    logo = models.CharField(max_length=30, verbose_name='类别标识')
    image = models.ImageField(upload_to='type', verbose_name='类别图片')
    status = models.SmallIntegerField(default=1, choices=((0, '禁用'), (1, '使用中')), verbose_name='类别状态')

    class Meta:
        db_table = 'novels_type'
        verbose_name = '小说类别表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.typename


class Novels(models.Model):
    '''小说表'''
    type = models.ForeignKey('NovelsType', verbose_name='小说类别', on_delete=models.CASCADE)
    uid = models.CharField(primary_key=True, max_length=40, unique=True, null=False)
    novel_name = models.CharField(max_length=20, verbose_name='小说书名')
    title = models.CharField(max_length=50, verbose_name='小说标题')
    desc = models.TextField(verbose_name='概述')
    author = models.CharField(max_length=20, verbose_name='作者')
    image = models.ImageField(upload_to='novels', verbose_name='小说图片')
    status = models.SmallIntegerField(default=1, choices=((0, '下线'), (1, '上线')), verbose_name='小说状态')
    is_delete = models.SmallIntegerField(default=0, choices=((0, '不删除'), (1, '删除')), verbose_name='是否删除')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now_add=True, verbose_name='更新时间')
    user = models.ForeignKey(to=User, on_delete=models.CASCADE,default='')

    class Meta:
        db_table = 'novels'
        verbose_name = '小说表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.novel_name


class ViceNovels(models.Model):
    '''小说副表'''
    novels = models.OneToOneField(to=Novels, on_delete=models.CASCADE)
    uid = models.CharField(primary_key=True, max_length=40, unique=True, null=False)
    hits = models.IntegerField(default=0, verbose_name='点击量')
    collection = models.IntegerField(default=0, verbose_name='收藏量')

    class Meta:
        db_table = 'novels_vice'
        verbose_name = '小说副表'
        verbose_name_plural = verbose_name


class Chapter(models.Model):
    '''小说章节表'''
    novels = models.ForeignKey(to=Novels, on_delete=models.CASCADE)
    uid = models.CharField(primary_key=True, max_length=40, unique=True, null=False)
    chaptername = models.CharField(max_length=20, verbose_name='章节名称')
    path = models.CharField(max_length=200, verbose_name='存储路径',default='')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    # text=HTMLField(verbose_name='章节正文',default='')

    class Meta:
        db_table = 'novels_chapter'
        verbose_name = '小说章节表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.chaptername


class Collection(models.Model):
    '''小说收藏表'''
    novels = models.ForeignKey(to=Novels, on_delete=models.CASCADE)
    uid = models.CharField(primary_key=True, max_length=40, unique=True, null=False)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    Collec_time = models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')

    class Meta:
        db_table = 'novels_collection'
        verbose_name = '小说收藏表'
        verbose_name_plural = verbose_name


class Hits(models.Model):
    '''小说点赞表'''
    novels = models.ForeignKey(to=Novels, on_delete=models.CASCADE)
    uid = models.CharField(primary_key=True, max_length=40, unique=True, null=False)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    hits_time = models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')

    class Meta:
        db_table = 'novels_hits'
        verbose_name = '小说点赞表'
        verbose_name_plural = verbose_name

class IndexBanner(models.Model):
    '''首页中的推荐'''
    novels = models.ForeignKey(to=Novels, on_delete=models.CASCADE, verbose_name='小说书名')
    image = models.ImageField(upload_to='banner', verbose_name='小说推荐图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'index_banner'
        verbose_name = '首页推荐图'
        verbose_name_plural = verbose_name

class MyBookrack(models.Model):
    '''我的书架'''
    user = models.ForeignKey(to=User,on_delete=models.CASCADE)
    novels = models.ForeignKey(to=Novels, on_delete=models.CASCADE)
    chapters_uid = models.IntegerField(verbose_name='章节id',null=True)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间',null=False)
    is_delete = models.SmallIntegerField(default=0, choices=((0, '不删除'), (1, '删除')), verbose_name='是否删除')

    class Meta:
        db_table = 'mybookrack'
        verbose_name = '我的书架表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user.username

novels/views.py
import uuid
from alembic import context
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, NoReverseMatch
from novels.models import NovelsType, IndexBanner, Novels, Chapter, MyBookrack, Hits
from user.models import User
from django.core.cache import cache
import logging
from django.contrib.auth import logout

logger = logging.getLogger('log')


# 首页
def index(request):
    '''登录判断'''
    user = request.session.get('username')

    if user:
        user = User.objects.filter(username=user).first()
        # 在首页中，判断是否在另一个浏览器登录了，从cache中取出登陆时存入的key
        liulanqi_key = cache.get('liulanqi:' + user.uid)
        logger.info('缓存中的key为：{}----浏览器中的key为:{}'.format(liulanqi_key, request.COOKIES['liulanqi_key']))
        # 校验当前浏览器中cookie中取出的key是否与cache中取出的key不一致
        if request.COOKIES['liulanqi_key'] != liulanqi_key:
            logging.info('该用户已经在其他地方登录了，该浏览器下线')
            logout(request)
            return redirect(reverse("user:login"))

    '''所有类别'''
    types = NovelsType.objects.all()

    '''推荐'''
    indexnovels = IndexBanner.objects.all().order_by('-index')

    '''最近更新的小说'''
    update_novels = Novels.objects.filter(status=1).order_by('-update_time')[:10]

    '''最新添加'''
    add_novels = Novels.objects.filter(status=1).order_by('-add_time')[:5]

    return render(request, 'novel/index.html', locals())


# 搜索
def search(request):
    types = NovelsType.objects.all()
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    if request.method == 'POST':
        searchsub = request.POST.get('searchsub')
        error_msg = ''
        if not searchsub:
            error_msg = '请输入关键词'
            return render(request, 'novel/search_result.html', {'error_msg': error_msg})
        else:
            novels_list = Novels.objects.filter(Q(name__icontains=searchsub) | Q(author__icontains=searchsub))
            # novels_author_list = Novels.objects.filter(author__icontains=searchsub)
            if novels_list:
                return render(request, 'novel/search_result.html', locals())
            else:
                return render(request, 'novel/search_result.html', {'msg': '无搜索结果'})
    return render(request, 'novel/search_result.html', locals())


# 小说详情页
def novel_detail(request, gid):
    types = NovelsType.objects.all()
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    novel = Novels.objects.get(uid=gid)
    if user:
        hits_novel = Hits.objects.filter(user_id=user.uid, novels_id=gid)
        if hits_novel:
            hits_novel = '已点赞'

    '''推荐阅读'''
    new_novels = Novels.objects.filter(type=novel.type).order_by('-add_time')[:2]

    '''最新章节'''
    new_chapter = Chapter.objects.filter(novels_id=gid).order_by('-add_time').first()

    logger.info('{}'.format(locals()))

    return render(request, 'novel/detail.html', locals())


# 小说正文
def novel_body(request, uid):
    types = NovelsType.objects.all()
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    chapter = Chapter.objects.get(uid=uid)
    # file_name = 'D:\\novels\\{}{}.txt'.format(chapter.uid,chapter.chaptername)
    file_name = 'C:\\Users\\xinxi\\PycharmProjects\\Scrapy_Novels\\novels\\novels\\file\\{}\\{}.txt'.format(chapter,
                                                                                                            chapter.chaptername)
    with open(file_name, encoding='utf-8') as file_obj:
        content = file_obj.read()
    return render(request, 'novel/novel_body.html', locals())


# 我的书架之加入书架
def add_bookrack(request):
    uid = request.GET.get('novelUid')
    novel = Novels.objects.get(uid=uid)
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    if user:
        mybookrack_novel = MyBookrack.objects.filter(user_id=user.uid, novels_id=uid, is_delete=0)
        mybookrack_novel1 = MyBookrack.objects.filter(user_id=user.uid, novels_id=uid, is_delete=1)
        if mybookrack_novel:
            return JsonResponse({'status': '402'})
        else:
            if mybookrack_novel1:
                mybookrack_novel1.update(is_delete=0)
            else:
                mybookrack = MyBookrack.objects.create(novels_id=uid, user_id=user.uid, is_delete=0)
                if mybookrack:
                    return JsonResponse({'status': '200'})
                else:
                    return JsonResponse({'status': '401'})


# 加入书签
def add_chapter(request):
    uid = request.GET.get('chapterUid')
    chapter = Chapter.objects.get(uid=uid)

    username = request.session.get('username')
    user = User.objects.filter(username=username).first()

    chapter = Chapter.objects.filter(uid=uid).first()
    novels_id = chapter.novels_id
    new_chapter = Chapter.objects.filter(novels_id=novels_id).last()
    chaptername = chapter.chaptername
    if user:
        mybookrack_chapter = MyBookrack.objects.filter(user_id=user.uid, novels_id=novels_id).first()
        logging.info('要查询的对象：{}'.format(mybookrack_chapter))
        if mybookrack_chapter:
            mybookrack_chapter.chapters_uid = uid
            mybookrack_chapter.is_delete = 0
            mybookrack_chapter.save()
            return JsonResponse({'status': '402'})
        else:
            mybookrack = MyBookrack.objects.create(chapters_uid=uid, user_id=user.uid, novels_id=novels_id, is_delete=0)
            if mybookrack:
                return JsonResponse({'status': '200'})
            else:
                return JsonResponse({'status': '401'})


# 展示我的书架
def show_bookrack(request):
    types = NovelsType.objects.all()
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    mybookrack = MyBookrack.objects.filter(user_id=user.uid, is_delete=0).all()
    count = mybookrack.count()
    print('count', count)
    novel_list = []
    chapter_list = []
    if mybookrack:
        for novel in mybookrack:
            new_chapter = Chapter.objects.filter(novels_id=novel.novels.uid).order_by('-add_time').first()
            uid = novel.chapters_uid
            chapter = Chapter.objects.filter(uid=uid).first()
            novel_list.append(new_chapter)
        dabao = zip(mybookrack, novel_list)
    return render(request, 'novel/show_bookrack.html', locals())


# 我的书架之删除
def delete_collect(request, uid):
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    MyBookrack_novel = MyBookrack.objects.filter(novels_id=uid, user_id=user.uid).first()
    MyBookrack_novel.is_delete = '1'
    MyBookrack_novel.save()
    return redirect(reverse('novels:show_bookrack'))


# 小说分类展示
def category_show(request, tid):
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()

    types = NovelsType.objects.all()
    type = NovelsType.objects.filter(id=tid).first()
    novels = Novels.objects.filter(type_id=tid, status=1).order_by("-add_time")

    # 分页功能
    paginator = Paginator(novels, 2)  # 每一页显示的条数
    page = request.GET.get('page', '1')  # 获取传递的页码数，默认显示为1
    try:
        page = int(page)  # page类型转换
    except Exception as err:
        page = 1
    # paginator.num_pages  # aginator.num_pages表示一共可以分的总页码数
    page_obj = paginator.page(page)  # 获取page对象
    # page_obj.has_next()  #获取下一页
    # page_obj.has_previous() #获取上一页
    # paginator.page_range
    return render(request, 'novel/category_show.html', locals())


# 点赞
def novel_hits(request):
    novel_uid = request.GET.get('novelUid')
    # novel = Novels.objects.get(uid=uid)
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    hits_novel = Hits.objects.filter(user_id=user.uid, novels_id=novel_uid)
    if hits_novel:
        hits_novel.delete()
        return JsonResponse({'status': '402'})
    else:
        uid = str(uuid.uuid4().hex)
        hits = Hits.objects.create(novels_id=novel_uid, user_id=user.uid, uid=uid)
        if hits:
            return JsonResponse({'status': '200'})
        else:
            return JsonResponse({'status': '401'})


# 排行榜单
def ranking_list(request):
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    # 小说推荐列表
    indexnovels = IndexBanner.objects.all().order_by('-index')

    # 最近更新小说列表
    update_novels = Novels.objects.all().order_by('-update_time')
    return render(request, 'novel/ranking_list.html', locals())


# 全部小说
def all_novels(request):
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    # 奇幻、玄幻小说
    novels1 = Novels.objects.filter(Q(type_id=1) | Q(type_id=7)).order_by('-add_time')

    # 武侠、仙侠、修真小说
    novels2 = Novels.objects.filter(Q(type_id=2) | Q(type_id=8) | Q(type_id=9)).order_by('-add_time')

    # 言情、都市小说
    novels3 = Novels.objects.filter(Q(type_id=10) | Q(type_id=3)).order_by('-add_time')

    # 历史、军事、穿越小说
    novels4 = Novels.objects.filter(Q(type_id=11) | Q(type_id=12) | Q(type_id=4)).order_by('-add_time')

    # 游戏、竞技、网游小说
    novels5 = Novels.objects.filter(Q(type_id=13) | Q(type_id=14) | Q(type_id=5)).order_by('-add_time')

    # 异灵、科幻小说
    novels6 = Novels.objects.filter(Q(type_id=15) | Q(type_id=6)).order_by('-add_time')
    return render(request, 'novel/all_novels.html', locals())


# 作者新增小说
def author_edit(request):
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    types = NovelsType.objects.all()
    if request.method == 'POST':
        uid = str(uuid.uuid4().hex)
        name = request.POST.get('name')
        title = request.POST.get('title')
        desc = request.POST.get('desc')

templates/novel/author_edit.html
{% extends 'base.html' %}
{% block title %}
    添加小说页
{% endblock %}
{% block content %}
    <form enctype="multipart/form-data" action="{% url 'novels:author_edit' %}" method="post" id="novels_form"
          novalidate="">
        {% csrf_token %}
        <div>
            <fieldset class="module aligned ">
                <div class="form-row field-type">
                    <div>
                        <label class="required" for="id_type">小说类别:</label>
                        <select name="type" required="" id="id_type">
                            <option value="" selected="">---------</option>
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.typename }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-row field-name">
                    <div>
                        <label class="required" for="id_name">小说书名:</label>
                        <input type="text" name="name" class="vTextField" maxlength="20" required="" id="id_name">
                    </div>
                </div>
                <div class="form-row field-title">
                    <div>
                        <label class="required" for="id_title">小说标题:</label>
                        <input type="text" name="title" class="vTextField" maxlength="50" required="" id="id_title">
                    </div>
                </div>
                <div class="form-row field-desc">
                    <div>
                        <label class="required" for="id_desc">概述:</label>
                        <textarea name="desc" cols="40" rows="10" class="vLargeTextField" required=""
                                  id="id_desc"></textarea>
                    </div>
                </div>
                <div class="form-row field-author">
                    <div>
                        <label class="required" for="id_author">作者:</label>
                        <input type="text" name="author" class="vTextField" maxlength="20" required="" id="id_author">
                    </div>
                </div>
                <div class="form-row field-image">
                    <div>
                        <label class="required" for="id_image">小说图片:</label>
                        <input type="file" name="image" required="" id="id_image">
                    </div>
                </div>
                <div class="form-row field-status">
                </div>
            </fieldset>
            <div class="submit-row">
                <input type="submit" value="保存" class="default" name="_save">
            </div>
        </div>
    </form>
{% endblock %}
{% block search %}
{% endblock %}

templates/novel/category_show.html
{% extends 'base.html' %}
{% block title %}
    小说章节详情页
{% endblock %}
{% block content %}
    <div class="main">
        <div id="centerl">
            <div id="content">
                <div id="main">
                    <div id="hotcontent">
                        <div class="listdht">
                            <div class="listdht_top">
                                <a href="{% url 'novels:index' %}">琴香书阁库</a> &gt; {{ type.typename }}小说 &gt; 列表
                            </div>
                        </div>
                        <div class="ll">
                            {% for novel in page_obj.object_list %}
                                <div class="item">
                                    <div class="image"><a href="{% url 'novels:detail' novel.uid %}">
                                        <img src="{{ MEDIA_URL }}{{ novel.image }}" alt="{{ novel.name }}" width="120"
                                             height="150"></a></div>
                                    <dl>
                                        <dt><span>作者：{{ novel.author }}</span>&nbsp&nbsp<a
                                            href="{% url 'novels:detail' novel.uid %}">书名：{{ novel.name }}</a></dt>
                                        <dd> {{ novel.title }}</dd>
                                    </dl>
                                    <div class="clear"></div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="pages" style="padding-top:5px">
                        <div class="pagelink" id="pagelink">
                            {% if page_obj.has_previous %}
                                <a href="{% url 'novels:category_show' type.id %}?page={{ page_obj.previous_page_number }}"
                                   class="pgroup">&lt;上一页</a>
                            {% else %}
                                <a href="{% url 'novels:category_show' type.id %}?page=1" class="pgroup">上一页</a>
                            {% endif %}
                            {% for i in page_obj.paginator.page_range %}
                                <a href="{% url 'novels:category_show' type.id %}?page={{ i }}"
                                    {% if page_obj.number == i %} style="font-weight:bolder" {% endif %}>{{ i }}</a>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <a href="{% url 'novels:category_show' type.id %}?page={{ page_obj.next_page_number }}"
                                   class="next">下一页&gt;</a>
                            {% else %}
                                <a href="{% url 'novels:category_show' type.id %}?page={{ page_obj.paginator.num_pages }}"
                                   class="next">下一页</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/novel/detail.html
{% extends 'base.html' %}
{% block title %}
    小说章节详情页
{% endblock %}
{% block content %}
    <div class="box_con">
        <div class="con_top">
            <div id="bdshare" class="bdshare_b" style="line-height: 12px;"></div>
            <a href="/">琴香书阁库</a> &gt; {{ novel.type.typename }}小说 &gt; {{ novel.novel_name }}最新章节列表
        </div>
        <div id="maininfo">
            <div id="info">
                <h1>{{ novel.novel_name }}</h1>
                <p>作&nbsp;&nbsp;&nbsp;&nbsp;者：{{ novel.author }}</p>
                <p>动&nbsp;&nbsp;&nbsp;&nbsp;作：<a href="#" id="add_bookrack">加入书架</a>,
                    <a href="#" id="novel_hit">{{ hits_novel | default:'点赞' }}</a>,
                    <a href="#footer">直达底部</a></p>
                <p>更新时间：{{ novel.update_time }}</p>
                <p>最新章节：<a href="#" target="_blank">{{ new_chapter | default:'暂无更新'}}</a></p>
            </div>
            <div id="intro">
                <p> 小说概述：{{ novel.desc }}</p>
            </div>
        </div>
        <div id="sidebar">
            <div id="fmimg"><img alt="{{ novel.name }}" src="{{ MEDIA_URL }}{{ novel.image }}" width="120" height="150"
                                 onerror="src=''{{ MEDIA_URL }}/novels/nocover.jpg"><span class="b"></span></div>
        </div>
        <div id="listtj">&nbsp;推荐阅读：
            {% for novel in new_novels %}
                <a href="{% url 'novels:detail' novel.uid %}" target="_blank">{{ novel.novel_name }}</a>、
            {% endfor %}
        </div>
    </div>
    <div class="box_con">
        <div id="list">
            {% for chapter in novel.chapter_set.all %}
                <dl>
                    <dd><a href="{% url 'novels:novelbody' chapter.uid %}">   {{ chapter.chaptername }}</a></dd>
                </dl>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block myjs %}
    <script>
        //加入书架
        $("#add_bookrack").click(function () {
            $.getJSON("{% url 'novels:add_bookrack' %}", {novelUid:{{novel.uid}}},
                function (data) {
                    if (data.status == '400') {
                        location.href = "{% url 'user:login' %}"
                    } else if (data.status == '200') {
                        alert('加入书架成功')
                    } else if (data.status == '402') {
                        alert('已加入书架')
                    }
                })
        });
        //点赞
        $("#novel_hit").click(function () {
            $.getJSON("{% url 'novels:novel_hits' %}", {novelUid:{{novel.uid}}},
                function (data) {
                    if (data.status == '400') {
                        location.href = "{% url 'user:login' %}"
                    } else if (data.status == '200') {
                        $("#novel_hit").text("已点赞")
                    } else if (data.status == '402') {
                        $("#novel_hit").text("点赞")
                    }
                    else{
                        alert('点赞失败')
                    }
                })
        })
    </script>
{% endblock %}

templates/novel/show_author_novels.html
{% extends 'base.html' %}
{% block title %}
    作者小说展示页面
{% endblock %}
{% block content %}
    <div id="main">
        <table class="grid" width="80%" align="center" border="1px">
            <tbody>
            <tr align="center">
                <th width="5%">类别</th>
                <th width="17%">文章名称</th>
                <th width="30%">文章概述</th>
                <th width="7%">作者</th>
                <th width="7%">状态</th>
                <th width="13%">封面图片</th>
                <th width="10%">添加时间</th>
                <th width="10%">操作</th>
            </tr>
            {% for novel in novels %}
                <tr align="center">
                    <td>
                        <span>{{ novel.type.typename }}</span>
                    </td>
                    <td>
                        <a href="{% url 'novels:detail' novel.uid %}">{{ novel.novel_name }}</a>
                    </td>
                    <td>
                        <span>{{ novel.desc }}</span>
                    </td>
                    <td>
                        <span>{{ novel.author }}</span>
                    </td>
                    <td>
                        <span>{{ novel.get_status_display}}</span>
                    </td>
                    <td>
                        <img src="{{ novel.image }}" alt="" style="width: 30px;height: 40px
">
                    </td>
                    <td>{{ novel.add_time }}</td>
                    <td class="nowrap">
                        <a href="javascript:if(confirm('确实要将本书删除么？')) document.location='{% url 'novels:author_delete_novel' novel.uid %}';"
                           id="del">删除</a>
                        <a href="{% url 'novels:author_add_capther' novel.uid %}" id="add">新增章节</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block search %}
{% endblock %}

templates/novel/show_bookrack.html
{% extends 'base.html' %}
{% block title %}
    小说章节详情页
{% endblock %}
{% block content %}
    <div id="main">
        <div class="gridtop" align="center">
            目前：书架有{{ count | default:'0' }}本；
            {% if count == 0 or None%}
            <p style="color: #ff461f">还没有小说，快去加入吧!</p>
            {% endif %}
        </div>
        <table class="grid" width="80%" align="center" border="1px">
            <tbody>
            <tr align="center">
                <th width="21%">文章名称</th>
                <th width="30%">最新章节</th>
                <th width="30%">书签</th>
                <th width="7%">添加时间</th>
                <th width="7%">操作</th>
            </tr>
            {% for mybookrack,novel_list in dabao %}
                <tr align="center">
                    <td>
                        <a href="{% url 'novels:detail' mybookrack.novels.uid %}">{{ mybookrack.novels.name }}</a>
                    </td>
                    <td>
                        <span><a href="#">{{ novel_list|default:'暂无更新' }}</a></span>
                    </td>
                    <td>
                        <span><a href="#">{{ mybookrack.chapters_uid|default:'' }}</a></span>
                    </td>
                    <td>{{ mybookrack.add_time }}</td>
                    <td class="nowrap">
                        <a href="javascript:if(confirm('确实要将本书移出书架么？')) document.location='{% url 'novels:delete_collect' mybookrack.novels.uid %}';" id="del">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}