Qinxiangshuge/urls.py
from django.contrib import admin
from django.urls import path, include

from novels.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('user/', include('user.urls', namespace='user')),
    path('novels/', include('novels.urls', namespace='novels')),
]

novels/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.views import serve
from django.urls import path, include

from Qinxiangshuge.settings import MEDIA_ROOT
from novels.views import *

app_name = 'novels'

urlpatterns = [
    url(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    url(r'^tinymce/', include('tinymce.urls')),
    path('index', index, name='index'),
    path('search', search, name='search'),
    path('detail/<str:gid>', novel_detail, name='detail'),
    path('novelbody/<str:uid>', novel_body, name='novelbody'),
    path('add_bookrack', add_bookrack, name='add_bookrack'),
    path('show_bookrack', show_bookrack, name='show_bookrack'),
    path('add_chapter', add_chapter, name='add_chapter'),
    path('delete_collect/<str:uid>', delete_collect, name='delete_collect'),
    path('category_show/<str:tid>', category_show, name='category_show'),
    path('novel_hits', novel_hits, name='novel_hits'),
    path('all_novels', all_novels, name='all_novels'),
    path('ranking_list', ranking_list, name='ranking_list'),
    path('author_edit', author_edit, name='author_edit'),
    path('author_add_capther/<str:uid>', author_add_capther, name='author_add_capther'),
    path('show_author_novels', show_author_novels, name='show_author_novels'),
    path('author_delete_novel/<str:uid>', author_delete_novel, name='author_delete_novel'),
]

user/urls.py
from django.urls import path

from user.views import user_login, user_register, user_send_code, user_draw, find_pwd, modify_pwd, user_logout,test_baidu

app_name = 'user'

urlpatterns = [
    path('login', user_login, name='login'),
    path('register', user_register, name='register'),
    path('send_code', user_send_code, name='send_code'),
    path('draw', user_draw, name='draw'),
    path('find_pwd', find_pwd, name='find_pwd'),
    path('modify_pwd', modify_pwd, name='modify_pwd'),
    path('logout', user_logout, name='logout'),
    path('test_report', test_baidu, name='test_baidu'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css">
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
</head>
{% block mycss %}
{% endblock %}
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">琴香书阁</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {#            <ul class="nav navbar-nav">#}
            {#                <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>#}
            {#                <li><a href="#">|</a></li>#}
            {#                <li><a href="#">联系我们</a></li>#}
            {#            </ul>#}

            {% if user and not visible %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">
                        <blink>欢迎您：</blink>
                        <em style="color: red">{{ user.username }}</em></a></li>
                    <li><a href="#">|</a></li>
                    <li><a href="{% url 'user:logout' %}">退出</a></li>
                </ul>
            {% elif visible %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'user:login' %}">登录</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'user:login' %}">登录</a></li>
                    <li><a href="#">|</a></li>
                    <li><a href="{% url 'user:register' %}">注册</a></li>
                </ul>
            {% endif %}
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% block navigation %}
    <div class="header podcast-header">
        <div class="container header-container">
            <nav class="navbar navbar-default navbar-inverse" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#phprt-main-nav">
                            <span class="sr-only"><font style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">切换导航</font></font></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="phprt-main-nav">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'novels:index' %}"><font style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">首页</font></font></a></li>
                            <li><a href="{% url 'novels:show_bookrack' %}"><font style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">我的书架</font></font></a></li>
                            <li><a href="{% url 'novels:category_show' 1 %}"><font
                                style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">玄幻小说</font></font></a></li>
                            <li><a href="{% url 'novels:category_show' 2 %}"><font
                                style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">修真小说</font></font></a></li>
                            <li><a href="{% url 'novels:category_show' 3 %}"><font
                                style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">都市小说</font></font></a></li>
                            <li><a href="{% url 'novels:category_show' 4 %}"><font
                                style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">穿越小说</font></font></a></li>
                            <li><a href="{% url 'novels:category_show' 5 %}"><font
                                style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">网游小说</font></font></a></li>
                            <li><a href="{% url 'novels:category_show' 6 %}"><font
                                style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">科幻小说</font></font></a></li>
                            <li><a href="{% url 'novels:ranking_list' %}"><font style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">排行榜单</font></font></a></li>
                            <li><a href="{% url 'novels:all_novels' %}"><font style="vertical-align: inherit;"><font
                                style="vertical-align: inherit;">全部小说</font></font></a></li>
                            {% if user.is_author == 1 %}
                                <li><a href="{% url 'novels:author_edit' %}"><font style="vertical-align: inherit;"><font
                                    style="vertical-align: inherit;">我是作者</font></font></a></li>
                                <li><a href="{% url 'novels:show_author_novels' %}"><font style="vertical-align: inherit;"><font
                                    style="vertical-align: inherit;">发布的小说</font></font></a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
{% endblock %}
{% block content %}
{% endblock %}
{% block search %}
    <div>
        <form class="navbar-form navbar-left" action="{% url 'novels:search' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" placeholder="搜索书名/作者" name="searchsub">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
        </form>
    </div>
{% endblock %}
{% block myjs %}
{% endblock %}
</body>
</html>