Qinxiangshuge/urls.py
from django.contrib import admin
from django.urls import path, include

from novels.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('user/', include('user.urls', namespace='user')),
    path('novels/', include('novels.urls', namespace='novels')),
]

user/urls.py
from django.urls import path

from user.views import user_login, user_register, user_send_code, user_draw, find_pwd, modify_pwd, user_logout,test_baidu

app_name = 'user'

urlpatterns = [
    path('login', user_login, name='login'),
    path('register', user_register, name='register'),
    path('send_code', user_send_code, name='send_code'),
    path('draw', user_draw, name='draw'),
    path('find_pwd', find_pwd, name='find_pwd'),
    path('modify_pwd', modify_pwd, name='modify_pwd'),
    path('logout', user_logout, name='logout'),
    path('test_report', test_baidu, name='test_baidu'),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    '''
    id
    username,password,last_login,is_superuser,first_name,last_name,email,is_staff,is_active,date_joined

    添加字段：
    phone_num,head_img,last_ip,uuid
    '''

    phone_num = models.CharField(max_length=11, unique=True, null=False, verbose_name='手机号码')
    head_img = models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='用户头像')
    last_ip = models.CharField(max_length=32, verbose_name='最后登录IP')
    uid = models.CharField(primary_key=True, max_length=40, unique=True, null=False)
    is_author = models.SmallIntegerField(default=0, choices=((0, '普通用户'), (1, '作者')), verbose_name='是否是作者')

    class Meta:
        db_table = 'user'
        verbose_name = '用户表'
        verbose_name_plural = verbose_name

user/views.py
import hashlib
import logging
import os
import random
import time
from io import BytesIO

import requests
from PIL import Image, ImageDraw, ImageFont, ImageFilter
from django.contrib.auth import logout
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth.views import login
from django.core.cache import cache
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from Qinxiangshuge import settings
from Qinxiangshuge.settings import PONT_PATH
from user.models import User

import uuid

logger = logging.getLogger('log')


# 用户登录
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('userName')
        password = request.POST.get('password')
        code = request.POST.get('code')
        code1 = request.session['code']
        rem_name = request.POST.get('rem_name')
        user = User.objects.filter(username=username).first()
        # 校验验证码是否正确
        if code.lower() == code1.lower():
            # 校验用户是否存在
            if user:
                # 校验用户是否是激活状态
                if user.is_active:
                    # 校验用户密码是否正确
                    if check_password(password, user.password):
                        response = redirect(reverse('novels:index'))
                        request.session['username'] = user.username
                        # 登录成功后，从客户端的cookie中取出key，并与user.uid绑定，存入cache中
                        liulanqi_key = request.COOKIES['liulanqi_key']
                        cache.set('liulanqi:' + user.uid, liulanqi_key)
                        if rem_name == 'on':
                            # 登录成功后，在cookie中设置值
                            response.set_cookie('uname', username)
                        return response
                    else:
                        return render(request, 'user/login.html', {'msg': '用户名和密码不正确'})
                else:
                    return render(request, 'user/login.html', {'msg': '用户名还未激活'})
            else:
                return render(request, 'user/login.html', {'msg': '用户名不存在'})
        else:
            return render(request, 'user/login.html', {'msg': '验证码有误'})
    else:
        username = request.COOKIES.get('uname', '')
        response = render(request, 'user/login.html', {'user': username})
        # 在登录GET请求时，从服务器端随机生成码，然后设置到浏览器的cookie中
        liulanqi_uuid = str(uuid.uuid1().hex)
        response.set_cookie('liulanqi_key', liulanqi_uuid)
        return response


# 用户注册
def user_register(request):
    if request.method == 'POST':
        username = request.POST.get('userName')
        email = request.POST.get('email')
        password = request.POST.get('password')
        phone = request.POST.get('phone')
        password = make_password(password)
        code = request.POST.get('code')
        is_author = request.POST.get('is_author')
        # 验证用户是否已注册
        user = User.objects.filter(username=username).first()
        if user:
            return render(request, 'user/register.html', {'msg': '用户名已被占用'})
        else:
            # 校验验证码是否正确
            # if code == request.session.get(phone):
            uid = str(uuid.uuid4().hex)
            user = User.objects.create(uid=uid, username=username, password=password, email=email, phone_num=phone)
            user.is_active = 1
            user.save()
            if is_author == 'on':
                user.is_author=1
                user.save()
            return redirect(reverse('user:login'))
            # else:
            #     return render(request, 'user/register.html', {'msg': '验证码有误'})
    else:
        visible = True
        return render(request, 'user/register.html',{'visible':visible})


# 获取验证码
def user_send_code(request):
    phone = request.GET.get('phone')
    # 寻求第三方服务：网易云信
    url = 'https://api.netease.im/sms/sendcode.action'
    headers = {}
    headers['Content-Type'] = 'application/x-www-form-urlencoded;charset=utf-8'
    headers['AppKey'] = 'c319e6d69853d2834d970fdd0d9b84b9'
    AppSecret = '03d4b504974c'
    Nonce = str(uuid.uuid4().hex)
    headers['Nonce'] = Nonce
    CurTime = str(int(time.time()))
    headers['CurTime'] = CurTime
    CheckSum = hashlib.sha1((AppSecret + Nonce + CurTime).encode('utf-8')).hexdigest()
    headers['CheckSum'] = CheckSum
    response = requests.post(url=url, data={'mobile': phone}, headers=headers)
    json_result = response.json()
    print(json_result)
    if json_result.get('code') == 200:
        request.session[phone] = json_result.get('obj')
        return JsonResponse({'msg': '短信发送成功！'})
    else:
        return JsonResponse({'msg': '短信发送失败！'})


# 登录验证码
def get_color():
    red = random.randint(0, 256)
    green = random.randint(0, 256)
    blue = random.randint(0, 256)
    return (red, green, blue)


def get_code():
    s = '1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM'
    code = ''
    for i in range(4):
        code += random.choice(s)
    return code


def user_draw(request):
    width = 120
    height = 34
    image_size = (width, height)
    image = Image.new('RGB', image_size, get_color())
    draw = ImageDraw.Draw(image)
    for i in range(10):
        begin = (random.randint(0, width), random.randint(0, height))
        end = (random.randint(0, width), random.randint(0, height))
        draw.line((begin, end), fill=get_color())

    for i in range(20):
        draw.point((random.randint(0, width), random.randint(0, height)), fill=get_color())

    code = get_code()
    myfont = ImageFont.truetype(font=os.path.join(PONT_PATH, 'verdana.ttf'), size=30)
    for i in range(4):
        distance_x = random.randint(30 * i, 30 * i + 5)
        distance_y = random.randint(0, 5)
        draw.text((distance_x, distance_y), code[i], font=myfont, fill=get_color())
    image = image.filter(ImageFilter.EDGE_ENHANCE_MORE)
    buffer = BytesIO()
    image.save(buffer, 'jpeg')
    buf_bytes = buffer.getbuffer()
    request.session['code'] = code
    return HttpResponse(buf_bytes, 'image/jpeg')


# 找回密码
def find_pwd(request):
    if request.method == 'POST':
        username = request.POST.get('userName')
        email = request.POST.get('email')
        user = User.objects.filter(username=username, email=email).first()
        logger.info('该用户需要进行找回密码{}'.format(user.uid))
        if user:
            # 生成token
            token = str(uuid.uuid4().hex)
            request.session[token] = user.uid
            logger.info('token的绑定情况为{}--->{}'.format(token, user.uid))
            path = 'http://127.0.0.1:8000/user/modify_pwd?token={}'.format(token)  # 信息格式化

            # 发送邮箱
            subject = '琴香书阁找回密码邮件'
            message = '''
                欢迎注册琴香书阁会员！亲爱的用户请赶快找回密码使用吧！
                <a href='{}'>点击重置密码</a>   
                如果链接不可用可以复制以下内容到浏览器激活：{}
    
                                                琴香书阁开发团队   
                '''.format(path, path)
            result = send_mail(subject=subject, message='', from_email=settings.EMAIL_HOST_USER,
                               recipient_list=[email, ],
                               html_message=message)
            if result == 1:
                return HttpResponse('邮箱发送成功')
            else:
                return HttpResponse('邮箱发送失败')
        else:
            return render(request, 'user/find_pwd.html', {'msg': '用户名或邮箱有误'})
    return render(request, 'user/find_pwd.html')


# 修改密码
def modify_pwd(request):
    if request.method == 'POST':
        new_password = request.POST.get('password')
        token = request.GET.get('token')

        # 获取session中值
        uid = request.session.get(token)
        logger.info('通过token：{}获取到的用户uid：{}'.format(token, uid))
        password = make_password(new_password)
        User.objects.filter(uid=uid).update(password=password)
        return HttpResponse('密码修改成功')
    else:
        token = request.GET.get('token')
        return render(request, 'user/modify_pwd.html', locals())


# 注销
def user_logout(request):
    logout(request)
    return redirect(reverse("user:login"))


def test_baidu(request):
    return render(request,'user/test.html')

templates/user/find_pwd.html
{% extends 'base.html' %}
{% block title %}
    找回密码
{% endblock %}
{% block navigation %}
{% endblock %}
{% block content %}
    <form action="{% url 'user:find_pwd' %}" id="form1" class="well"
          style="width: 30em; margin: auto; margin-top: 100px;" method="post">
        {% csrf_token %}
        <h3>找回密码</h3>
        <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="userName" name="userName" type="text" class="form-control" placeholder="用户名"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>
        <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="email" name="email" type="text" class="form-control" placeholder="邮箱"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>

        <p style="color: #ff461f">{{ msg }}</p>

        <button type="submit" class="btn btn-success btn-block">发送密码到邮箱</button>
        <a class="btn btn-sm btn-white btn-block" style="text-align: right;" th:href="@{register}"
           href="{% url 'user:login' %}"><h6>返回</h6></a>
    </form>
{% endblock %}
{% block search %}
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% block title %}
    用户登录
{% endblock %}
{% block navigation %}
{% endblock %}
{% block content %}
    <form action="{% url 'user:login' %}" id="form1" class="well"
          style="width: 30em; margin: auto; margin-top: 100px;" method="post">
        {% csrf_token %}
        <h3>用户登录</h3>
        <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="userName" name="userName" type="text" class="form-control" placeholder="用户名"
                   aria-describedby="sizing-addon1" value="{{ username }}"/>
        </div>
        <br/>
        <div class="input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-lock"></i></span>
            <input type="password" id="password" name="password" class="form-control" placeholder="密码"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>
        <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="code" name="code" type="text" class="form-control" placeholder="验证码"
                   aria-describedby="sizing-addon1" style="width: 200px; margin: auto;"/>
            &nbsp&nbsp&nbsp&nbsp&nbsp<img src="{% url 'user:draw' %}" alt="" id="pic">
        </div>
        <br/>
        <p style="color: #ff461f">{{ msg }}</p>
        <div class="well well-sm" style="text-align: center;">
            <input type="checkbox" name="rem_name"/> 记住用户名
            <a href="{% url 'user:find_pwd' %}">忘记密码</a>
        </div>
        <button type="submit" class="btn btn-success btn-block">登录</button>
        <a class="btn btn-sm btn-white btn-block" style="text-align: right;" th:href="@{register}"
           href="{% url 'user:register' %}"><h6>还没有账户？前往注册</h6></a>
    </form>
{% endblock %}
{% block myjs %}
    <script>
        $('#pic').click(function () {
            path = '{% url 'user:draw' %}?ran=' + Math.random();
            $(this).attr('src', path)
        });
    </script>
{% endblock %}
{% block search %}
{% endblock %}

templates/user/modify_pwd.html
{% extends 'base.html' %}
{% block title %}
    修改密码
{% endblock %}
{% block navigation %}
{% endblock %}
{% block content %}
    <form action="{% url 'user:modify_pwd' %}" id="form1" class="well"
          style="width: 30em; margin: auto; margin-top: 150px;" method="post">
        {% csrf_token %}
        <h3>修改密码</h3>
        <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="password" name="password" type="password" class="form-control" placeholder="输入新密码"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>
        <div class="input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-lock"></i></span> <input type="password"
                                                                      id="repassword" name="repassword"
                                                                      class="form-control" placeholder="输入确认密码"
                                                                      aria-describedby="sizing-addon1"/>
        </div>
        <input type="hidden" name="token" value="{{token}}">
        <br/>

        <button type="submit" class="btn btn-success btn-block">修改密码</button>
    </form>
{% endblock %}
{% block search %}
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% block title %}
    用户注册
{% endblock %}
{% block navigation %}
{% endblock %}
{% block content %}
    <form action="{% url 'user:register' %}" id="form1" class="well"
          style="width: 30em; margin: auto; margin-top: 30px;" method="post">
        {% csrf_token %}
        <h3>用户注册</h3>
        <div class="input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="userName" name="userName" type="text" class="form-control" placeholder="用户名"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>
        <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="email" name="email" type="text" class="form-control" placeholder="邮箱"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>
        <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="phone" name="phone" type="text" class="form-control" placeholder="手机号"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>
        <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
            <input id="code" name="code" type="text" class="form-control" placeholder="验证码"
                   aria-describedby="sizing-addon1" style="width: 235px; margin: auto; "/>
            &nbsp
            <button class="btn btn" type="button" name="send_code" id="send_code"/>
            获取验证码</button>
        </div>
        <br/>
        <div class="input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-lock"></i></span>
            <input type="password" id="password" name="password" class="form-control" placeholder="密码"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>
        <div class="input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1"><i
                  class="glyphicon glyphicon-lock"></i></span>
            <input type="password" id="repassword" name="repassword" class="form-control" placeholder="确认密码"
                   aria-describedby="sizing-addon1"/>
        </div>
        <br/>
        <p style="color: #ff461f">{{ msg }}</p>
        <div class="well well-sm" style="text-align: center;">
            <input type="checkbox" name="is_author"/> 是否为作者
        </div>
        <button type="submit" class="btn btn-success btn-block">立即注册</button>
    </form>
{% endblock %}

{% block myjs %}
    <script>
        $('#phone').blur(function () {
            click_phone()
        });

        function click_phone() {

            var phone = $("#phone").val();
            var ephone = $("#errorphone");
            /* 手机号码为空/不为空 */
            if (phone == "") {
                ephone.html("手机号码不为空。");
                return false;
            } else {
                ephone.html('');
            }
            /* 手机号码长度 */
            if (phone.length < 11 || phone.length > 11) {
                ephone.html("长度为11位。");
                return false;
            } else {
                ephone.html('');
            }
            return true;
        }

        $('#send_code').click(function () {
            //文本框中获取phone值
            var phone = $('#phone').val();
            click_phone();
            // 通过ajax发送请求
            $.getJSON('/user/send_code', {phone: phone}, function (data) {
                alert(data.msg)
            })
        });
    </script>
{% endblock %}
{% block search %}
{% endblock %}

templates/user/test.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>自动化测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         { }

/* -- heading ---------------------------------------------------------------------- */
h1 {
	font-size: 16pt;
	color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}

.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}

a.popup_link:hover {
    color: red;
}

.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    padding: 10px;
    background-color: #E6E6D6;
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    width: 500px;
}

}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
}
#header_row {
    font-weight: bold;
    color: white;
    background-color: #777;
}
#result_table td {
    border: 1px solid #777;
    padding: 2px;
}
#total_row  { font-weight: bold; }
.passClass  { background-color: #6c6; }
.failClass  { background-color: #c60; }
.errorClass { background-color: #c00; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }


/* -- ending ---------------------------------------------------------------------- */
#ending {
}

</style>

</head>
<body>
<script language="javascript" type="text/javascript"><!--
output_list = Array();

/* level - 0:Summary; 1:Failed; 2:All */
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level < 1) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level > 1) {
                tr.className = '';
            }
            else {
                tr.className = 'hiddenRow';
            }
        }
    }
}


function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        tid0 = 't' + cid.substr(1) + '.' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        if (toHide) {
            document.getElementById('div_'+tid).style.display = 'none'
            document.getElementById(tid).className = 'hiddenRow';
        }
        else {
            document.getElementById(tid).className = '';
        }
    }
}


function showTestDetail(div_id){
    var details_div = document.getElementById(div_id)
    var displayState = details_div.style.display
    // alert(displayState)
    if (displayState != 'block' ) {
        displayState = 'block'
        details_div.style.display = 'block'
    }
    else {
        details_div.style.display = 'none'
    }
}


function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

/* obsoleted by detail in <div>
function showOutput(id, name) {
    var w = window.open("", //url
                    name,
                    "resizable,scrollbars,status,width=800,height=450");
    d = w.document;
    d.write("<pre>");
    d.write(html_escape(output_list[id]));
    d.write("\n");
    d.write("<a href='javascript:window.close()'>close</a>\n");
    d.write("</pre>\n");
    d.close();
}
*/
--></script>

<div class='heading'>
<h1>自动化测试报告</h1>
<p class='attribute'><strong>Start Time:</strong> 2020-12-10 14:41:00</p>
<p class='attribute'><strong>Duration:</strong> 0:00:15.528620</p>
<p class='attribute'><strong>Status:</strong> Pass 1 Error 1</p>

<p class='description'></p>
</div>



<p id='show_detail_line'>Show
<a href='javascript:showCase(0)'>Summary</a>
<a href='javascript:showCase(1)'>Failed</a>
<a href='javascript:showCase(2)'>All</a>
</p>
<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row'>
    <td>Test Group/Test case</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
</tr>

<tr class='passClass'>
    <td>testcase1.BaiduTest</td>
    <td>1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td><a href="javascript:showClassDetail('c1',1)">Detail</a></td>
</tr>

<tr id='pt1.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_baidu</div></td>
    <td colspan='5' align='center'>pass</td>
</tr>

<tr class='errorClass'>
    <td>testcase2.BPMTest</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c2',1)">Detail</a></td>
</tr>

<tr id='ft2.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_BPM</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.1')" >
        error</a>

    <div id='div_ft2.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft2.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>

ft2.1: Traceback (most recent call last):
  File "C:\Users\xinxi\PycharmProjects\BPMselenium\src\testcase\testcase2.py", line 23, in test_BPM
    driver.find_element_by_id("userId$text").clear()
  File "D:\Envs\Django2020\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "D:\Envs\Django2020\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\Envs\Django2020\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Envs\Django2020\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userId$text"]"}
  (Session info: chrome=87.0.4280.88)

Traceback (most recent call last):
  File "C:\Users\xinxi\PycharmProjects\BPMselenium\src\testcase\testcase2.py", line 23, in test_BPM
    driver.find_element_by_id("userId$text").clear()
  File "D:\Envs\Django2020\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "D:\Envs\Django2020\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\Envs\Django2020\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Envs\Django2020\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userId$text"]"}
  (Session info: chrome=87.0.4280.88)



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='total_row'>
    <td>Total</td>
    <td>2</td>
    <td>1</td>
    <td>0</td>
    <td>1</td>
    <td>&nbsp;</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>

</body>
</html>